////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by genmodel, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package sys_dicts

//go:generate gormgen -structs Dict -input .
type Dict struct {
	Id        int32  `json:"id"`         //主键
	Title     string `json:"title"`      //字典标题
	DictKey   string `json:"dict_key"`   //字典Key
	DictType  int32  `json:"dict_type"`  //字典数据类型(1=>数字, 2=>字符, 3=>json)
	Module    string `json:"module"`     //模块名称
	IsDelete  int32  `json:"is_delete"`  //是否删除
	Remark    string `json:"remark"`     //备注
	CreatedAt int32  `json:"created_at"` //创建时间
	UpdatedAt int32  `json:"updated_at"` //更新时间

}

func (_ *Dict) TableName() string {
	return "sys_dicts"
}
