[Server]
name = "Web-demo"
port = 8889
cors = true

[mysql]
[mysql.read] # 从库信息，可读
    addr = '192.168.1.25:3306'      # MySQL 地址:端口
    user = 'root'                   # 用户名
    pass = 'HundyG63gF%42sdf'       # 密码
    name = 'shop'                   # 数据库名称
[mysql.write] # 主库信息，可读写
    addr = '192.168.1.25:3306'      # MySQL 地址:端口
    user = 'root'                   # 用户名
    pass = 'HundyG63gF%42sdf'       # 密码
    name = 'shop'                   # 数据库名称
[mysql.base] # 基础配置
    maxOpenConn = 10             # 最大打开的连接数
    maxIdleConn = 60             # 闲置的连接数
    connMaxLifeTime = 60         # 最大连接超时(单位:分)

[jwt]
secret = '21ddG1tdHyuJTrw7retY'  # JWT secret
expireDuration = 12              # JWT ExpiresAt 过期时间(单位:小时)
